from fpdf import FPDF
import os
import datetime
import pandas as pd
import tempfile

from streamlit import pdf

from streamlit import pdf


# =========================================================
# PDF THEME
# =========================================================
PRIMARY = (99, 102, 241)      # Indigo
ACCENT = (16, 185, 129)       # Emerald
TEXT = (55, 65, 81)           # Slate
MUTED = (148, 163, 184)       # Muted gray
ROW_ALT = (241, 245, 249)     # Light slate


# =========================================================
# BASE PDF CLASS
# =========================================================
class ReportPDF(FPDF):

    def header(self):
        self.set_fill_color(*PRIMARY)
        self.rect(0, 0, 210, 20, "F")

        self.set_text_color(255, 255, 255)
        self.set_font("DejaVu", "", 15)
        self.cell(0, 12, "Retirement Financial Summary", ln=True, align="C")
        self.ln(6)

    def footer(self):
        self.set_y(-12)
        self.set_text_color(*MUTED)
        self.set_font("DejaVu", "", 8)
        self.cell(0, 8, f"Generated by Future Finance Simulator · Page {self.page_no()}", align="C")

    def section(self, title):
        self.ln(6)
        self.set_text_color(*TEXT)
        self.set_font("DejaVu", "", 13)
        self.cell(0, 8, title, ln=True)
        self.set_draw_color(*MUTED)
        self.line(12, self.get_y(), 198, self.get_y())
        self.ln(4)

    def metric_row(self, label, value):
        self.set_text_color(*TEXT)
        self.set_font("DejaVu", "", 10)
        self.cell(90, 7, label)
        self.set_text_color(*ACCENT)
        self.cell(0, 7, value, ln=True)

    def table_header(self, headers, col_widths):
        self.set_fill_color(*PRIMARY)
        self.set_text_color(255, 255, 255)
        self.set_font("DejaVu", "", 10)
        for h, w in zip(headers, col_widths):
            self.cell(w, 8, h, border=1, fill=True)
        self.ln()

    def table_row(self, row, col_widths, fill=False):
        self.set_fill_color(*ROW_ALT)
        self.set_text_color(*TEXT)
        self.set_font("DejaVu", "", 9)
        for v, w in zip(row, col_widths):
            self.cell(w, 7, str(v), border=1, fill=fill)
        self.ln()


# =========================================================
# MAIN PDF GENERATOR
# =========================================================
from typing import Optional

def generate_financial_summary_pdf(
    username: str,
    base_context: dict,
    projection_df: pd.DataFrame,
    currency: str,
    *,
    income_expense_chart_png: Optional[bytes] = None,
    corpus_chart_png: Optional[bytes] = None,
    scenario_comparison_df: Optional[pd.DataFrame] = None,
):

    pdf = ReportPDF()
    pdf.set_auto_page_break(True, 15)

    # ---------------- Font ----------------
    font_path = os.path.join(
        os.path.dirname(__file__),
        "assets",
        "fonts",
        "DejaVuSans.ttf"
    )
    pdf.add_font("DejaVu", "", font_path, uni=True)
    pdf.set_font("DejaVu", "", 10)

    pdf.add_page()

    # =====================================================
    # META
    # =====================================================
    meta = base_context["_meta"]
    pdf.set_text_color(*TEXT)
    pdf.cell(0, 6, f"User: {username}", ln=True)
    pdf.cell(0, 6, f"Country: {meta['country_label']}", ln=True)
    pdf.cell(0, 6, f"Scenario: {meta['scenario']}", ln=True)
    pdf.cell(0, 6, f"Generated on: {datetime.date.today()}", ln=True)

    # =====================================================
    # KEY METRICS
    # =====================================================
    pdf.section("Key Metrics (Year 1)")

    y1 = projection_df.iloc[0]

    pdf.metric_row("Starting Corpus", f"{currency}{base_context['initial_corpus']['total']:,.0f}")
    pdf.metric_row("Annual Mandatory Expenses", f"{currency}{y1['AnnualMustExpenses']:,.0f}")
    pdf.metric_row("Annual Optional Expenses", f"{currency}{y1['AnnualOptionalExpenses']:,.0f}")
    pdf.metric_row("Net Income After Tax", f"{currency}{y1['NetIncomeAfterTax']:,.0f}")

    # =====================================================
    # CHARTS
    # =====================================================
    if income_expense_chart_png or corpus_chart_png:
        pdf.section("Visual Overview")

    def render_chart(png_bytes, title):
        if not png_bytes:
            return
        pdf.ln(2)
        pdf.set_text_color(*TEXT)
        pdf.set_font("DejaVu", "", 11)
        pdf.cell(0, 8, title, ln=True)

        with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
            tmp.write(png_bytes)
            tmp_path = tmp.name

        pdf.image(tmp_path, w=180)
        os.unlink(tmp_path)

    render_chart(income_expense_chart_png, "Income vs Expenses")
    render_chart(corpus_chart_png, "Corpus Growth Over Time")

    # =====================================================
    # PROJECTION TABLE
    # =====================================================
    pdf.section("Projection Snapshot (First 5 Years)")

    table = projection_df.head(5)
    headers = ["Year", "Total Income", "Total Expenses", "Ending Corpus"]
    widths = [20, 55, 55, 55]

    pdf.table_header(headers, widths)

    fill = False
    for _, r in table.iterrows():
        ending = r.get("EndingCorpus", r.get("Ending Corpus", 0))
        #pdf.cell(40, 8, f"{currency}{ending:,.0f}", border=1)

        pdf.table_row(
            [
                int(r["Year"]),
                f"{currency}{r['TotalIncome']:,.0f}",
                f"{currency}{r['TotalExpenses']:,.0f}",
                f"{currency}{ending:,.0f}",
            ],
            widths,
            fill,
        )
        fill = not fill

    # =====================================================
    # SCENARIO COMPARISON
    # =====================================================
    if scenario_comparison_df is not None and not scenario_comparison_df.empty:
        pdf.section("Scenario Comparison")

        headers = ["Scenario", "Ending Corpus", "Net Income (Y1)"]
        widths = [60, 60, 60]

        pdf.table_header(headers, widths)

        fill = False
        for _, r in scenario_comparison_df.iterrows():
            ending = r.get("EndingCorpus", r.get("Ending Corpus", 0))
            netincom = r.get("NetIncomeAfterTax", r.get("Year-1 Net Income", 0))
            pdf.table_row(
                [
                    r["Scenario"],
                    f"{currency}{ending:,.0f}",
                    f"{currency}{netincom:,.0f}",
                ],
                widths,
                fill,
            )
            fill = not fill

    # =====================================================
    # OUTPUT
    # =====================================================
    return bytes(pdf.output(dest="S"))
