from fpdf import FPDF
import os
import datetime
import pandas as pd
import tempfile

from streamlit import html, pdf

from streamlit import pdf


# =========================================================
# PDF THEME
# =========================================================
PRIMARY = (99, 102, 241)      # Indigo
ACCENT = (16, 185, 129)       # Emerald
TEXT = (55, 65, 81)           # Slate
MUTED = (148, 163, 184)       # Muted gray
ROW_ALT = (241, 245, 249)     # Light slate


# =========================================================
# BASE PDF CLASS
# =========================================================
class ReportPDF(FPDF):

    def header(self):
        self.set_fill_color(*PRIMARY)
        self.rect(0, 0, 210, 20, "F")

        self.set_text_color(255, 255, 255)
        self.set_font("DejaVu", "", 15)
        self.cell(0, 12, "Retirement Financial Summary", ln=True, align="C")
        self.ln(6)

    def footer(self):
        self.set_y(-12)
        self.set_text_color(*MUTED)
        self.set_font("DejaVu", "", 8)
        self.cell(0, 8, f"Generated by Future Finance Simulator · Page {self.page_no()}", align="C")

    def section(self, title):
        self.ln(6)
        self.set_text_color(*TEXT)
        self.set_font("DejaVu", "", 13)
        self.cell(0, 8, title, ln=True)
        self.set_draw_color(*MUTED)
        self.line(12, self.get_y(), 198, self.get_y())
        self.ln(4)

    def metric_row(self, label, value):
        self.set_text_color(*TEXT)
        self.set_font("DejaVu", "", 10)
        self.cell(90, 7, label)
        self.set_text_color(*ACCENT)
        self.cell(0, 7, value, ln=True)

    def table_header(self, headers, col_widths):
        self.set_fill_color(*PRIMARY)
        self.set_text_color(255, 255, 255)
        self.set_font("DejaVu", "", 10)
        for h, w in zip(headers, col_widths):
            self.cell(w, 8, h, border=1, fill=True)
        self.ln()

    def table_row(self, row, col_widths, fill=False):
        self.set_fill_color(*ROW_ALT)
        self.set_text_color(*TEXT)
        self.set_font("DejaVu", "", 9)
        for v, w in zip(row, col_widths):
            self.cell(w, 7, str(v), border=1, fill=fill)
        self.ln()


# =========================================================
# MAIN PDF GENERATOR
# =========================================================
from typing import Optional

def generate_financial_summary_pdf_old(
    username: str,
    base_context: dict,
    projection_df: pd.DataFrame,
    currency: str,
    *,
    income_expense_chart_png: Optional[bytes] = None,
    corpus_chart_png: Optional[bytes] = None,
    scenario_comparison_df: Optional[pd.DataFrame] = None,
):

    pdf = ReportPDF()
    pdf.set_auto_page_break(True, 15)

    # ---------------- Font ----------------
    font_path = os.path.join(
        os.path.dirname(__file__),
        "assets",
        "fonts",
        "DejaVuSans.ttf"
    )
    pdf.add_font("DejaVu", "", font_path, uni=True)
    pdf.set_font("DejaVu", "", 10)

    pdf.add_page()

    # =====================================================
    # META
    # =====================================================
    meta = base_context["_meta"]
    pdf.set_text_color(*TEXT)
    pdf.cell(0, 6, f"User: {username}", ln=True)
    pdf.cell(0, 6, f"Country: {meta['country_label']}", ln=True)
    pdf.cell(0, 6, f"Scenario: {meta['scenario']}", ln=True)
    pdf.cell(0, 6, f"Generated on: {datetime.date.today()}", ln=True)

    # =====================================================
    # KEY METRICS
    # =====================================================
    pdf.section("Key Metrics (Year 1)")

    y1 = projection_df.iloc[0]

    pdf.metric_row("Starting Corpus", f"{currency}{base_context['initial_corpus']['total']:,.0f}")
    pdf.metric_row("Annual Mandatory Expenses", f"{currency}{y1['AnnualMustExpenses']:,.0f}")
    pdf.metric_row("Annual Optional Expenses", f"{currency}{y1['AnnualOptionalExpenses']:,.0f}")
    pdf.metric_row("Net Income After Tax", f"{currency}{y1['NetIncomeAfterTax']:,.0f}")

    # =====================================================
    # CHARTS
    # =====================================================
    if income_expense_chart_png or corpus_chart_png:
        pdf.section("Visual Overview")

    def render_chart(png_bytes, title):
        if not png_bytes:
            return
        pdf.ln(2)
        pdf.set_text_color(*TEXT)
        pdf.set_font("DejaVu", "", 11)
        pdf.cell(0, 8, title, ln=True)

        with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
            tmp.write(png_bytes)
            tmp_path = tmp.name

        pdf.image(tmp_path, w=180)
        os.unlink(tmp_path)

    render_chart(income_expense_chart_png, "Income vs Expenses")
    render_chart(corpus_chart_png, "Corpus Growth Over Time")

    # =====================================================
    # PROJECTION TABLE
    # =====================================================
    pdf.section("Projection Snapshot (First 5 Years)")

    table = projection_df.head(5)
    headers = ["Year", "Total Income", "Total Expenses", "Ending Corpus"]
    widths = [20, 55, 55, 55]

    pdf.table_header(headers, widths)

    fill = False
    for _, r in table.iterrows():
        ending = r.get("EndingCorpus", r.get("Ending Corpus", 0))
        #pdf.cell(40, 8, f"{currency}{ending:,.0f}", border=1)

        pdf.table_row(
            [
                int(r["Year"]),
                f"{currency}{r['TotalIncome']:,.0f}",
                f"{currency}{r['TotalExpenses']:,.0f}",
                f"{currency}{ending:,.0f}",
            ],
            widths,
            fill,
        )
        fill = not fill

    # =====================================================
    # SCENARIO COMPARISON
    # =====================================================
    if scenario_comparison_df is not None and not scenario_comparison_df.empty:
        pdf.section("Scenario Comparison")

        headers = ["Scenario", "Ending Corpus", "Net Income (Y1)"]
        widths = [60, 60, 60]

        pdf.table_header(headers, widths)

        fill = False
        for _, r in scenario_comparison_df.iterrows():
            ending = r.get("EndingCorpus", r.get("Ending Corpus", 0))
            netincom = r.get("NetIncomeAfterTax", r.get("Year-1 Net Income", 0))
            pdf.table_row(
                [
                    r["Scenario"],
                    f"{currency}{ending:,.0f}",
                    f"{currency}{netincom:,.0f}",
                ],
                widths,
                fill,
            )
            fill = not fill

    # =====================================================
    # OUTPUT
    # =====================================================
    pdf_bytes = pdf.output(dest="S").encode("latin-1")
    return bytes(pdf_bytes)
    #return bytes(pdf.output(dest="S"))

##NOTE: The above function is the old version. The new version is more modular and supports additional features like charts and scenario comparisons. The old version is kept for reference and can be removed if not needed.

import asyncio
import datetime
import pandas as pd
from playwright.async_api import async_playwright


# =========================================================
# HTML TEMPLATE BUILDER
# =========================================================
import datetime



def build_financial_html(
    username,
    base_context,
    projection_df,
    currency,
    retirement_score=None,
    score_breakdown=None,
    advisor_advice=None,
    income_expense_chart_html="",
    corpus_chart_html="",
    tax_chart_html="",
    scenario_comparison_df=None,
    onetime_chart_html="",
    recurring_chart_html="",
    expense_growth_chart_html="",
):

    meta = base_context.get("_meta", {})
    country = meta.get("country_label", "")
    scenario = meta.get("scenario", "")
    today = datetime.date.today().strftime("%d %B %Y")

    y1 = projection_df.iloc[0]
    final = projection_df.iloc[-1]

    # -----------------------------------------------------
    # Scenario table HTML
    # -----------------------------------------------------
    scenario_table_html = ""
    if scenario_comparison_df is not None and not scenario_comparison_df.empty:
        scenario_table_html = scenario_comparison_df.to_html(
            index=False, classes="table", border=0
        )

    # -----------------------------------------------------
    # Score breakdown table
    # -----------------------------------------------------
    score_table = ""
    if score_breakdown:
        rows = "".join(
            f"<tr><td>{k}</td><td>{v}</td></tr>"
            for k, v in score_breakdown.items()
        )
        score_table = f"""
        <table class="table small">
        <tr><th>Metric</th><th>Score</th></tr>
        {rows}
        </table>
        """

    # -----------------------------------------------------
    # Advisor section
    # -----------------------------------------------------
    advisor_html = ""
    if advisor_advice:
        advisor_html = f"""
        <h2>Advisor Insights & Recommendations</h2>
        <div class="advisor-box">
        {advisor_advice}
        </div>
        """

    # =====================================================
    # HTML DOCUMENT
    # =====================================================
    html = f"""
<html>
<head>
<meta charset="utf-8">
<script src="https://cdn.plot.ly/plotly-2.30.0.min.js"></script>
<style>

body {{
    font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Arial;
    color:#111827;
    line-height:1.6;
}}

h1,h2,h3 {{
    color:#1f2937;
}}

p {{
    color:#374151;
}}

.section {{
    margin-top:35px;
}}

.section-desc {{
    color:#6b7280;
    font-size:14px;
    margin-bottom:12px;
}}

.page-break {{
    page-break-before: always;
}}

.table {{
    width:100%;
    border-collapse:collapse;
    margin-top:12px;
}}

.table th {{
    background:#f3f4f6;
    padding:8px;
    text-align:left;
}}

.table td {{
    padding:8px;
    border-bottom:1px solid #e5e7eb;
}}

.small td {{
    padding:5px;
}}

.highlight {{
    background:#eef2ff;
    padding:14px;
    border-left:5px solid #6366f1;
    border-radius:6px;
}}

.advisor-box {{
    background:#f0fdf4;
    padding:18px;
    border-left:5px solid #22c55e;
    border-radius:6px;
}}

.score-card {{
    background:#eef2ff;
    padding:25px;
    border-radius:10px;
    text-align:center;
    font-size:34px;
    font-weight:bold;
    margin-top:20px;
}}

.cover-page {{
    text-align:center;
    margin-top:140px;
}}

.cover-page h1 {{
    font-size:38px;
}}

.cover-score {{
    font-size:72px;
    font-weight:bold;
    color:#6366f1;
    margin-top:40px;
}}

.chart-block {{
    width: 100%;
    margin: 20px 0 40px 0;
    padding: 10px;
    border: 1px solid #e5e7eb;
    border-radius: 8px;
    page-break-inside: avoid;
    break-inside: avoid;
}}

.plotly-graph-div {{
    margin: auto !important;
}}

@media print {{

    .chart-block {{
        page-break-inside: avoid;
        break-inside: avoid;
    }}

    .page-break {{
        page-break-before: always;
    }}

}}

</style>
</head>

<body>

<!-- ================================================= -->
<!-- COVER PAGE -->
<!-- ================================================= -->

<div class="cover-page">
    <h1>Financial Life Planning Report</h1>
    <p>Future Finance Simulator</p>

    <p><b>Client:</b> {username}</p>
    <p><b>Country:</b> {country}</p>
    <p><b>Scenario:</b> {scenario}</p>
    <p><b>Date:</b> {today}</p>

    {f'<div class="cover-score">{retirement_score}/100</div>' if retirement_score else ""}
</div>

<div class="page-break"></div>

<!-- ================================================= -->
<!-- EXECUTIVE SUMMARY -->
<!-- ================================================= -->

<h2>Executive Summary</h2>

<p>
This report evaluates your long-term financial outlook by projecting income,
expenses, investment growth, taxation, and savings sustainability under
structured economic assumptions.
</p>

<div class="highlight">
Net income after tax (Year 1): {currency}{y1['NetIncomeAfterTax']:,.0f}
</div>

<p>
Ending projected corpus: <b>{currency}{final['EndingCorpus']:,.0f}</b>
</p>

<!-- ================================================= -->
<!-- FINANCIAL SCORE -->
<!-- ================================================= -->

<div class="section">
<h2>Financial Health Score</h2>

{f'<div class="score-card">{retirement_score} / 100</div>' if retirement_score else ""}

{score_table}
</div>

<div class="page-break"></div>

<!-- ================================================= -->
<!-- SCENARIO COMPARISON -->
<!-- ================================================= -->

<div class="section">
<h2>Scenario Comparison</h2>
<p class="section-desc">
Comparison of long-term financial outcomes across planning strategies.
</p>
{scenario_table_html}
</div>

<!-- ================================================= -->
<!-- INCOME VS EXPENSE -->
<!-- ================================================= -->

<div class="section">
<h2>Income vs Expense Projection</h2>
<p class="section-desc">
Tracks whether projected income remains sufficient to meet rising expenses.
</p>
<div class="chart-block">
    <h3>Income vs Expenses</h3>
    { income_expense_chart_html }
</div>
</div>

<div class="section">
<h2>Expense Growth Over Time</h2>
<p class="section-desc">
Illustrates how essential and lifestyle expenses grow over time.
</p>
<div class="chart-block">
    <h3>Expenses Growth Over Time</h3>
    { expense_growth_chart_html }
</div>

</div>

<div class="page-break"></div>

<!-- ================================================= -->
<!-- INVESTMENT GROWTH -->
<!-- ================================================= -->

<div class="section">
<h2>Investment & Corpus Growth</h2>
<p class="section-desc">
Shows projected long-term change in investment corpus.
</p>
<div class="chart-block">
    <h3>Investment & Corpus Growth</h3>
    { corpus_chart_html }
</div>
</div>

<!-- ================================================= -->
<!-- EXPENSE STRUCTURE -->
<!-- ================================================= -->

<div class="section">
<h2>Expense Structure</h2>

<h3>One-Time Expenses</h3>
<div class="chart-block">
    <h3>One-Time Expenses</h3>
    { onetime_chart_html}
</div>

<h3>Recurring Expenses (Year 1)</h3>
<div class="chart-block">
    <h3>Recurring Expenses</h3>
    { recurring_chart_html}
</div>
</div>

<!-- ================================================= -->
<!-- TAX IMPACT -->
<!-- ================================================= -->

<div class="section">
<h2>Tax Impact</h2>
<p class="section-desc">
Illustrates tax outflows and net income over time.
</p>
<div class="chart-block">
    <h3>Tax Impact Over Time</h3>
    { tax_chart_html }
</div>
</div>

<!-- ================================================= -->
<!-- PROJECTION TABLE -->
<!-- ================================================= -->

<div class="section">
<h2>Yearly Projection Table</h2>
{projection_df.to_html(index=False, classes="table")}
</div>

{advisor_html}

<!-- ================================================= -->
<!-- ASSUMPTIONS -->
<!-- ================================================= -->

<div class="section">
<h2>Projection Assumptions</h2>
<ul>
<li>Inflation adjusted annually</li>
<li>Investment returns based on selected scenario</li>
<li>Expenses grow with inflation</li>
<li>Taxes computed using applicable rules</li>
</ul>
</div>

</body>
</html>
"""
    return html

def build_financial_html_old2(
    username: str,
    base_context: dict,
    projection_df: pd.DataFrame,
    currency: str,
    retirement_score=None,
    score_breakdown=None,
    advisor_advice=None,
    income_expense_chart_html: str = "",
    corpus_chart_html: str = "",
    tax_chart_html: str = "",
    scenario_comparison_df: pd.DataFrame | None = None,
    onetime_chart_html: str = "",
    recurring_chart_html: str = "",
    expense_growth_chart_html: str = "",
):

    import datetime

    meta = base_context["_meta"]
    y1 = projection_df.iloc[0]

    total_tax_paid = projection_df["TotalTax"].sum()
    year1_tax = projection_df.iloc[0]["TotalTax"]
    effective_tax_rate = (
        year1_tax / max(projection_df.iloc[0]["TotalIncome"], 1)
    ) * 100

    # ---------------- SCORE BREAKDOWN ----------------
    breakdown_rows = ""
    if score_breakdown:
        for k, v in score_breakdown.items():
            breakdown_rows += f"<tr><td>{k}</td><td>{v}</td></tr>"

    # ---------------- ADVISOR ----------------
    advisor_html = ""
    if advisor_advice:
        summary = advisor_advice.get("summary", "")
        positives = advisor_advice.get("positives", [])
        warnings = advisor_advice.get("warnings", [])
        recs = advisor_advice.get("recommendations", [])

        advisor_html += "<h2>Advisor Insights</h2>"

        if summary:
            advisor_html += f"<p><b>Summary:</b> {summary}</p>"

        if positives:
            advisor_html += "<h3>What’s Working Well</h3><ul>"
            for p in positives:
                advisor_html += f"<li>{p}</li>"
            advisor_html += "</ul>"

        if warnings:
            advisor_html += "<h3>Warnings</h3><ul>"
            for w in warnings:
                advisor_html += f"<li>{w}</li>"
            advisor_html += "</ul>"

        if recs:
            advisor_html += "<h3>Recommendations</h3><ul>"
            for r in recs:
                advisor_html += f"<li>{r}</li>"
            advisor_html += "</ul>"

    # ---------------- PROJECTION TABLE ----------------
    projection_rows = ""
    for _, r in projection_df.head(5).iterrows():
        ending = r.get("EndingCorpus", r.get("Ending Corpus", 0))
        projection_rows += f"""
        <tr>
            <td>{int(r["Year"])}</td>
            <td>{currency}{r["TotalIncome"]:,.0f}</td>
            <td>{currency}{r["TotalExpenses"]:,.0f}</td>
            <td>{currency}{ending:,.0f}</td>
        </tr>
        """

    # ---------------- SCENARIO TABLE ----------------
    scenario_rows = ""
    if scenario_comparison_df is not None and not scenario_comparison_df.empty:
        for _, r in scenario_comparison_df.iterrows():
            ending = r.get("EndingCorpus", r.get("Ending Corpus", 0))
            net = r.get("NetIncomeAfterTax", r.get("Year-1 Net Income", 0))
            scenario_rows += f"""
            <tr>
                <td>{r["Scenario"]}</td>
                <td>{currency}{ending:,.0f}</td>
                <td>{currency}{net:,.0f}</td>
            </tr>
            """

    # ---------------- HTML ----------------
    html = f"""
<html>
<head>
<meta charset="utf-8">
<script src="https://cdn.plot.ly/plotly-2.30.0.min.js"></script>
<style>
@page {{
    size: A4;
    margin: 25mm 20mm 20mm 20mm;
}}

html, body {{
    font-family: Arial, sans-serif;
    color: #374151;
    height: auto !important;
    overflow: visible !important;
}}

/* FORCE NATURAL VERTICAL FLOW */
body * {{
   /* position: relative !important;*/
    max-height: none !important;
}}

/* HEADERS */
h1 {{
    background:#6366f1;
    color:white;
    padding:15px;
    text-align:center;
}}

h2 {{
    border-bottom:2px solid #e5e7eb;
    padding-bottom:5px;
    margin-top:40px;

    /* avoid section split */
    page-break-after: avoid;
}}

/* TABLES */
table {{
    width:100%;
    border-collapse: collapse;
    margin-top:40px;
    page-break-inside:auto;
}}

tr {{
    page-break-inside: avoid;
    page-break-after: auto;
    
}}

th {{
    background:#6366f1;
    color:white;
    padding:8px;
    text-align:left;
}}

td {{
    border:1px solid #e5e7eb;
    padding:8px;
}}

/* SCORE */
.score-box {{
    background:#eef2ff;
    padding:20px;
    font-size:22px;
    text-align:center;
    border-radius:10px;
    margin-top:20px;
}}

/* ⭐ CRITICAL — CHART PRINT SAFE */
.chart {{
    margin-top:30px;
    width:100%;

    /* 🔥 CRITICAL — never split chart */
    page-break-inside: avoid !important;
    break-inside: avoid !important;

    /* ensure browser treats as solid block */
    display: block;

    /* optional but recommended */
    overflow: visible !important;
}}

/* FORCE PAGE BREAK UTILITY */
.page-break {{
    page-break-before: always;
}}

.plotly-graph-div {{
    height: 500px !important;
}}

/* ENSURE CONTENT NEVER CLIPS */
div {{
    overflow: visible !important;
}}

</style>
</head>

<body>


<h1>Retirement Financial Summary</h1>

<p><b>User:</b> {username}</p>
<p><b>Country:</b> {meta['country_label']}</p>
<p><b>Scenario:</b> {meta['scenario']}</p>
<p><b>Generated:</b> {datetime.date.today()}</p>

{"<div class='score-box'>Retirement Readiness Score: " + str(retirement_score) + " / 100</div>" if retirement_score else ""}

{"<h2>Score Breakdown</h2><table><tr><th>Category</th><th>Score</th></tr>" + breakdown_rows + "</table>" if breakdown_rows else ""}

<h2>Key Metrics (Year 1)</h2>
<p>Starting Corpus: {currency}{base_context['initial_corpus']['total']:,.0f}</p>
<p>Annual Mandatory Expenses: {currency}{y1['AnnualMustExpenses']:,.0f}</p>
<p>Annual Optional Expenses: {currency}{y1['AnnualOptionalExpenses']:,.0f}</p>
<p>Net Income After Tax: {currency}{y1['NetIncomeAfterTax']:,.0f}</p>

<h2>Tax Impact Analysis</h2>
<p>Total Tax Paid Over Projection: {currency}{total_tax_paid:,.0f}</p>
<p>Year-1 Tax Liability: {currency}{year1_tax:,.0f}</p>
<p>Effective Tax Rate (Year-1): {effective_tax_rate:.1f}%</p>

.chart-page {{
    page-break-before: always;
}}

<h2>Visual Overview</h2>
<div class="chart-page"></div>
<h3>Tax Impact</h3>
<div class="chart">{tax_chart_html}</div>
<h3>Income vs Expenses</h3>
<div class="chart">{income_expense_chart_html}</div>
<h3>Corpus Growth</h3>
<div class="chart">{corpus_chart_html}</div>
<h3>One-Time Expenses Distribution</h3>
<div class="chart">{onetime_chart_html}</div>
<h3>Recurring Expenses (Year 1)</h3>
<div class="chart">{recurring_chart_html}</div>
<h3>Expense Growth Over Time</h3>
<div class="chart">{expense_growth_chart_html}</div>

<h2>Projection Snapshot</h2>
<table>
<tr>
<th>Year</th>
<th>Total Income</th>
<th>Total Expenses</th>
<th>Ending Corpus</th>
</tr>
{projection_rows}
</table>

{"<h2>Scenario Comparison</h2><table><tr><th>Scenario</th><th>Ending Corpus</th><th>Net Income (Y1)</th></tr>" + scenario_rows + "</table>" if scenario_rows else ""}

{advisor_html}

</body>
</html>
"""
    return html

def build_financial_html_old(
    username: str,
    base_context: dict,
    projection_df: pd.DataFrame,
    currency: str,
    retirement_score=None,
    score_breakdown=None,
    advisor_advice=None,
    income_expense_chart_html: str = "",
    corpus_chart_html: str = "",
    tax_chart_html: str = "",
    scenario_comparison_df: pd.DataFrame | None = None,
):

    meta = base_context["_meta"]
    y1 = projection_df.iloc[0]

    total_tax_paid = projection_df["TotalTax"].sum()
    year1_tax = projection_df.iloc[0]["TotalTax"]
    effective_tax_rate = (
        year1_tax / max(projection_df.iloc[0]["TotalIncome"], 1)
    ) * 100
    #print(f"DEBUG: Year 1 Total Income: {projection_df.iloc[0]['TotalIncome']}, Year 1 Tax: {year1_tax}, Effective Tax Rate: {effective_tax_rate:.2f}%")
    # -------------------------------------------------
    # SCORE BREAKDOWN TABLE
    # -------------------------------------------------
    breakdown_rows = ""
    if score_breakdown:
        for k, v in score_breakdown.items():
            breakdown_rows += f"""
            <tr>
                <td>{k}</td>
                <td>{v}</td>
            </tr>
            """

    # -------------------------------------------------
    # ADVISOR CONTENT
    # -------------------------------------------------
    advisor_html = ""

    if advisor_advice:
        summary = advisor_advice.get("summary", "")

        positives = advisor_advice.get("positives", [])
        warnings = advisor_advice.get("warnings", [])
        recs = advisor_advice.get("recommendations", [])

        advisor_html += "<h2>Advisor Insights</h2>"

        if summary:
            advisor_html += f"<p><b>Summary:</b> {summary}</p>"

        if positives:
            advisor_html += "<h3>What’s Working Well</h3><ul>"
            for p in positives:
                advisor_html += f"<li>{p}</li>"
            advisor_html += "</ul>"

        if warnings:
            advisor_html += "<h3>Warnings</h3><ul>"
            for w in warnings:
                advisor_html += f"<li>{w}</li>"
            advisor_html += "</ul>"

        if recs:
            advisor_html += "<h3>Recommendations</h3><ul>"
            for r in recs:
                advisor_html += f"<li>{r}</li>"
            advisor_html += "</ul>"

    # -------------------------------------------------
    # PROJECTION TABLE
    # -------------------------------------------------
    projection_rows = ""
    for _, r in projection_df.head(5).iterrows():
        ending = r.get("EndingCorpus", r.get("Ending Corpus", 0))
        projection_rows += f"""
        <tr>
            <td>{int(r["Year"])}</td>
            <td>{currency}{r["TotalIncome"]:,.0f}</td>
            <td>{currency}{r["TotalExpenses"]:,.0f}</td>
            <td>{currency}{ending:,.0f}</td>
        </tr>
        """

    # -------------------------------------------------
    # SCENARIO TABLE
    # -------------------------------------------------
    scenario_rows = ""
    if scenario_comparison_df is not None and not scenario_comparison_df.empty:
        for _, r in scenario_comparison_df.iterrows():
            ending = r.get("EndingCorpus", r.get("Ending Corpus", 0))
            net = r.get("NetIncomeAfterTax", r.get("Year-1 Net Income", 0))
            scenario_rows += f"""
            <tr>
                <td>{r["Scenario"]}</td>
                <td>{currency}{ending:,.0f}</td>
                <td>{currency}{net:,.0f}</td>
            </tr>
            """

    # -------------------------------------------------
    # HTML TEMPLATE
    # -------------------------------------------------
    html = f"""
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            @page {{
                size: A4;
                margin: 20mm;
            }}

            body {{
                page-break-inside: auto;
            }}

            table {{
                page-break-inside: avoid;
            }}

            .chart {{
                page-break-inside: avoid;
            }}

            .score-box {{
                page-break-inside: avoid;
            }}

            h1, h2, h3 {{
                page-break-after: avoid;
            }}

            ul {{
                page-break-inside: avoid;
            }}

            .section {{
                page-break-inside: avoid;
                margin-bottom: 25px;
            }}

            body {{
                font-family: Arial, sans-serif;
                margin: 40px;
                color: #374151;
            }}
            h1 {{
                background:#6366f1;
                color:white;
                padding:15px;
                text-align:center;
            }}
            h2 {{
                border-bottom:2px solid #e5e7eb;
                padding-bottom:5px;
                margin-top:30px;
            }}
            table {{
                width:100%;
                border-collapse: collapse;
                margin-top:10px;
            }}
            th {{
                background:#6366f1;
                color:white;
                padding:8px;
                text-align:left;
            }}
            td {{
                border:1px solid #e5e7eb;
                padding:8px;
            }}
            .score-box {{
                background:#eef2ff;
                padding:20px;
                font-size:22px;
                text-align:center;
                border-radius:10px;
                margin-top:20px;
            }}
            .chart {{
                margin-top:25px;
            }}
        </style>
    </head>

    <body>

        <h1>Retirement Financial Summary</h1>

        <p><b>User:</b> {username}</p>
        <p><b>Country:</b> {meta['country_label']}</p>
        <p><b>Scenario:</b> {meta['scenario']}</p>
        <p><b>Generated:</b> {datetime.date.today()}</p>

        {"<div class='score-box'>Retirement Readiness Score: " + str(retirement_score) + " / 100</div>" if retirement_score else ""}

        {f'''
        <h2>Score Breakdown</h2>
        <table>
            <tr><th>Category</th><th>Score</th></tr>
            {breakdown_rows}
        </table>
        ''' if breakdown_rows else ""}

        <h2>Key Metrics (Year 1)</h2>
        <p>Starting Corpus: {currency}{base_context['initial_corpus']['total']:,.0f}</p>
        <p>Annual Mandatory Expenses: {currency}{y1['AnnualMustExpenses']:,.0f}</p>
        <p>Annual Optional Expenses: {currency}{y1['AnnualOptionalExpenses']:,.0f}</p>
        <p>Net Income After Tax: {currency}{y1['NetIncomeAfterTax']:,.0f}</p>

        <h2>Tax Impact Analysis</h2>

        <p>Total Tax Paid Over Projection: {currency}{total_tax_paid:,.0f}</p>
        <p>Year-1 Tax Liability: {currency}{year1_tax:,.0f}</p>
        <p>Effective Tax Rate (Year-1): {effective_tax_rate:.1f}%</p>

        <div class="chart">
            {tax_chart_html}
        </div>

        <h2>Visual Overview</h2>
        <div class="chart">{income_expense_chart_html}</div>
        <div class="chart">{corpus_chart_html}</div>

        <h2>Projection Snapshot</h2>
        <table>
            <tr>
                <th>Year</th>
                <th>Total Income</th>
                <th>Total Expenses</th>
                <th>Ending Corpus</th>
            </tr>
            {projection_rows}
        </table>

        {f'''
        <h2>Scenario Comparison</h2>
        <table>
            <tr>
                <th>Scenario</th>
                <th>Ending Corpus</th>
                <th>Net Income (Y1)</th>
            </tr>
            {scenario_rows}
        </table>
        ''' if scenario_rows else ""}

        {advisor_html}

    </body>
    </html>
    """

    return html

# =========================================================
# PLAYWRIGHT PDF GENERATOR
# =========================================================
async def _html_to_pdf_bytes_old(html: str) -> bytes:
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page()
        await page.set_content(html, wait_until="networkidle")

        pdf_bytes = await page.pdf(
            format="A4",
            print_background=True,
            margin={"top": "20px", "bottom": "20px", "left": "20px", "right": "20px"},
        )

        await browser.close()
        return pdf_bytes

#from playwright.sync_api import sync_playwright

from playwright.async_api import async_playwright

async def generate_pdf(html_file, output_pdf):
    #print("DEBUG: Starting PDF generation with Playwright...")
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page()

        # Load file
        #-await page.goto(f"file://{html_file}", wait_until="networkidle")
        await page.set_content(html_file, wait_until="networkidle")


        # Render like browser (NOT print)
        await page.emulate_media(media="screen")

        # Wait for charts / JS
        await page.wait_for_timeout(2000)

        # Fix pagination + clipping
        await page.add_style_tag(content="""
        * {
            page-break-inside: avoid !important;
            break-inside: avoid !important;
        }

        .chart-container, canvas, .plotly {
            overflow: visible !important;
            height: auto !important;
            min-height: 400px !important;
        }
        """)

        # Generate PDF
        pdf_bytes = await page.pdf(
            format="A4",
            print_background=True,
            prefer_css_page_size=True,
            display_header_footer=True,
            margin={"top":"15mm","bottom":"15mm","left":"10mm","right":"10mm"},
            header_template="""
            <div style="
                width:100%;
                font-size:20px;
                padding:0 20px;
                color:#6b7280;
                text-align:center;
                border-bottom:1px solid #e5e7eb;
            ">
                Retirement Financial Summary · Future Finance Simulator
            </div>
            """,
            footer_template="""
            <div style="
                width:100%;
                font-size:15px;
                padding:0 20px;
                color:#9ca3af;
                text-align:right;
            ">
                Page <span class="pageNumber"></span> of <span class="totalPages"></span>
            </div>
            """
        )
        
        await browser.close()
        #print(f"DEBUG: PDF generated and saved to {output_pdf}")
        return pdf_bytes

from playwright.sync_api import sync_playwright

def _html_to_pdf_bytes(html: str) -> bytes:
    print("DEBUG: In html_to_pdf_bytes...")
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()

        # Load HTML
        page.set_content(html, wait_until="networkidle")

        # -----------------------------
        # WAIT FOR PLOTLY FULL RENDER
        # -----------------------------
        page.wait_for_function("""
            () => {
                if (!window.Plotly) return false;

                const charts = document.querySelectorAll('.plotly-graph-div');
                if (charts.length === 0) return true;

                return Array.from(charts).every(
                    c => c._fullLayout && c._fullLayout._plots
                );
            }
        """)

        # -----------------------------
        # WAIT UNTIL PAGE HEIGHT STOPS CHANGING
        # -----------------------------
        print("DEBUG: Waiting for page height to stabilize...")
        page.wait_for_function("""
            () => {
                return new Promise(resolve => {
                    let last = document.body.scrollHeight;
                    let stable = 0;

                    const interval = setInterval(() => {
                        const now = document.body.scrollHeight;

                        if (now === last) {
                            stable++;
                            if (stable >= 3) {
                                clearInterval(interval);
                                resolve(true);
                            }
                        } else {
                            stable = 0;
                            last = now;
                        }
                    }, 300);
                });
            }
        """)

        # -----------------------------
        # FORCE FINAL LAYOUT
        # -----------------------------
        page.evaluate("""
            window.dispatchEvent(new Event('resize'));
        """)

        page.wait_for_timeout(800)

        # -----------------------------
        # GENERATE PDF
        # -----------------------------
        pdf_bytes = page.pdf(
            format="A4",
            print_background=True,
            prefer_css_page_size=True,
            display_header_footer=True,
            margin={
                "top": "20mm",
                "bottom": "20mm",
                "left": "15mm",
                "right": "15mm",
            },

            header_template="""
            <div style="
                width:100%;
                font-size:20px;
                padding:0 20px;
                color:#6b7280;
                text-align:center;
                border-bottom:1px solid #e5e7eb;
            ">
                Retirement Financial Summary · Future Finance Simulator
            </div>
            """,

            footer_template="""
            <div style="
                width:100%;
                font-size:15px;
                padding:0 20px;
                color:#9ca3af;
                text-align:right;
            ">
                Page <span class="pageNumber"></span> of <span class="totalPages"></span>
            </div>
            """
        )
      
        browser.close()
        return pdf_bytes

def _html_to_pdf_bytes_old2(html: str) -> bytes:

    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()

        # Load HTML and WAIT for everything
        page.set_content(html, wait_until="networkidle")

        # ⭐ CRITICAL — wait for Plotly charts to render
        page.wait_for_timeout(2000)

        # If charts exist, wait until Plotly finished drawing
        try:
            page.wait_for_function(
                "window.Plotly !== undefined"
            )
        except:
            pass

        # ⭐ ensure full height render
        page.evaluate("document.body.style.zoom = '1.0'")

        pdf_bytes = page.pdf(
            format="A4",
            print_background=True,
            margin={
                "top": "20mm",
                "bottom": "20mm",
                "left": "15mm",
                "right": "15mm",
            }
        )

        browser.close()
        return pdf_bytes

def generate_financial_summary_pdf_playwright(
    username,
    base_context,
    projection_df,
    currency,
    retirement_score=None,
    score_breakdown=None,
    advisor_advice=None,
    income_expense_chart_html="",
    corpus_chart_html="",
    tax_chart_html="",     # ⭐ NEW
    scenario_comparison_df=None,
    onetime_chart_html: str = "",
    recurring_chart_html: str = "",
    expense_growth_chart_html: str = "",
):
    print("DEBUG 2: Building HTML for PDF...")
    html = build_financial_html(
        username,
        base_context,
        projection_df,
        currency,
        retirement_score=retirement_score,
        score_breakdown=score_breakdown,
        advisor_advice=advisor_advice,
        income_expense_chart_html=income_expense_chart_html,
        corpus_chart_html=corpus_chart_html,
        tax_chart_html=tax_chart_html,
        scenario_comparison_df=scenario_comparison_df,
        onetime_chart_html=onetime_chart_html,
        recurring_chart_html=recurring_chart_html,
        expense_growth_chart_html=expense_growth_chart_html,
    )
    #with open("debug.html", "w") as f:
    #    f.write(html)

    # return _html_to_pdf_bytes(html)
    # generate_pdf(html, "output.pdf")
    print("DEBUG: Starting PDF generation...")
    return asyncio.run(generate_pdf(html, "output.pdf"))

#from weasyprint import HTML
#import datetime


def generate_financial_summary_pdf_weasyprint(
        username,
        base_context,
        projection_df,
        currency,
        *,
        retirement_score=None,
        score_breakdown=None,
        advisor_advice=None,
        income_expense_chart_html=None,
        corpus_chart_html=None,
        tax_chart_html=None,
        scenario_comparison_df=None,
    ):

        meta = base_context["_meta"]
        y1 = projection_df.iloc[0]

        # ---------------------------------------------------
        # SCORE INTERPRETATION
        # ---------------------------------------------------
        if retirement_score is not None:
            if retirement_score >= 80:
                score_text = "You are on track for a confident retirement."
                score_color = "#16a34a"
            elif retirement_score >= 60:
                score_text = "Moderately prepared. Some adjustments recommended."
                score_color = "#f59e0b"
            else:
                score_text = "Plan requires strengthening."
                score_color = "#ef4444"
        else:
            score_text = ""
            score_color = "#6b7280"

        # ---------------------------------------------------
        # SCORE BREAKDOWN TABLE
        # ---------------------------------------------------
        breakdown_rows = ""
        if score_breakdown:
            for k, v in score_breakdown.items():
                breakdown_rows += f"<tr><td>{k}</td><td>{v}</td></tr>"

        # ---------------------------------------------------
        # PROJECTION TABLE
        # ---------------------------------------------------
        projection_rows = ""
        for _, r in projection_df.head(10).iterrows():
            ending = r.get("EndingCorpus", r.get("Ending Corpus", 0))
            projection_rows += f"""
            <tr>
                <td>{int(r['Year'])}</td>
                <td>{currency}{r['TotalIncome']:,.0f}</td>
                <td>{currency}{r['TotalExpenses']:,.0f}</td>
                <td>{currency}{ending:,.0f}</td>
            </tr>
            """

        # ---------------------------------------------------
        # SCENARIO TABLE
        # ---------------------------------------------------
        scenario_html = ""
        if scenario_comparison_df is not None and not scenario_comparison_df.empty:
            rows = ""
            for _, r in scenario_comparison_df.iterrows():
                rows += f"""
                <tr>
                    <td>{r['Scenario']}</td>
                    <td>{currency}{r['Ending Corpus']:,.0f}</td>
                    <td>{currency}{r['Year-1 Net Income']:,.0f}</td>
                </tr>
                """

            scenario_html = f"""
            <div class="section">
                <h2>Scenario Comparison</h2>
                <table>
                    <tr><th>Scenario</th><th>Ending Corpus</th><th>Year-1 Net Income</th></tr>
                    {rows}
                </table>
            </div>
            """

        # ---------------------------------------------------
        # ADVISOR PANEL HTML
        # ---------------------------------------------------
        advice_html = ""
        if advisor_advice:
            def render_list(title, items, color):
                if not items:
                    return ""
                lis = "".join(f"<li>{i}</li>" for i in items)
                return f"<h3 style='color:{color}'>{title}</h3><ul>{lis}</ul>"

            advice_html = f"""
            <div class="section">
                <h2>Advisor Insights</h2>
                <p><b>Summary:</b> {advisor_advice.get("summary","")}</p>
                {render_list("What’s Working Well", advisor_advice.get("positives",[]), "#16a34a")}
                {render_list("Warnings", advisor_advice.get("warnings",[]), "#f59e0b")}
                {render_list("Recommendations", advisor_advice.get("recommendations",[]), "#2563eb")}
            </div>
            """

        # ---------------------------------------------------
        # HTML DOCUMENT
        # ---------------------------------------------------
        html = f"""
    <html>
    <head>
    <meta charset="utf-8">
    <style>

    @page {{ margin: 25mm; }}
   
    body {{
        font-family: Arial, sans-serif;
        color:#374151;
    }}

    .cover {{
        text-align:center;
        margin-top:120px;
    }}

    .score {{
        font-size:60px;
        font-weight:bold;
        color:{score_color};
    }}

    .section {{
        margin-top:40px;
    }}

    table {{
        width:100%;
        border-collapse:collapse;
        margin-top:10px;
    }}

    th {{
        background:#6366f1;
        color:white;
        padding:8px;
    }}

    td {{
        padding:7px;
        border-bottom:1px solid #e5e7eb;
    }}

    .chart {{
        margin-top:20px;
    }}

    .page-break {{
        page-break-before:always;
    }}

    </style>
    </head>

    <body>

    <!-- COVER PAGE -->
    <div class="cover">
    <h1>Retirement Financial Plan</h1>
    <h3>{username}</h3>
    <p>{meta["country_label"]}</p>
    <p>Scenario: {meta["scenario"]}</p>
    <p>{datetime.date.today()}</p>

    <div class="score">{retirement_score}/100</div>
    <p>{score_text}</p>
    </div>

    <div class="page-break"></div>

    <!-- SCORECARD -->
    <div class="section">
    <h2>Retirement Readiness Score Breakdown</h2>
    <table>
    <tr><th>Category</th><th>Score</th></tr>
    {breakdown_rows}
    </table>
    </div>

    <!-- SNAPSHOT -->
    <div class="section">
    <h2>Financial Snapshot (Year 1)</h2>
    <p>Starting Corpus: {currency}{base_context['initial_corpus']['total']:,.0f}</p>
    <p>Mandatory Expenses: {currency}{y1['AnnualMustExpenses']:,.0f}</p>
    <p>Optional Expenses: {currency}{y1['AnnualOptionalExpenses']:,.0f}</p>
    <p>Net Income: {currency}{y1['NetIncomeAfterTax']:,.0f}</p>
    </div>

    <!-- CHARTS -->
    {f"<div class='section'><h2>Income vs Expenses</h2>{income_expense_chart_html}</div>" if income_expense_chart_html else ""}
    {f"<div class='section'><h2>Corpus Trajectory</h2>{corpus_chart_html}</div>" if corpus_chart_html else ""}
    {f"<div class='section'><h2>Tax Impact</h2>{tax_chart_html}</div>" if tax_chart_html else ""}

    {scenario_html}
    {advice_html}

    <div class="section">
    <h2>Projection Table</h2>
    <table>
    <tr><th>Year</th><th>Total Income</th><th>Total Expenses</th><th>Ending Corpus</th></tr>
    {projection_rows}
    </table>
    </div>

    <div class="section">
    <p style="font-size:10px;color:#6b7280">
    This report is an estimate based on assumptions and projections. Not investment advice.
    </p>
    </div>

    </body>
    </html>
    """

        return HTML(string=html).write_pdf()
